export default function Faq() {
  return (
    <div className="bg-black text-white min-h-screen p-10">
      <h1 className="text-4xl text-red-600 mb-6">FAQ</h1>
      <h2 className="text-2xl mb-2">How do I get an invitation key?</h2>
      <p>Keys are generated by Hebi admins using <code>/genkey</code>.</p>

      <h2 className="text-2xl mt-6 mb-2">What happens if I share my key?</h2>
      <p>Your IP will be banned permanently.</p>

      <h2 className="text-2xl mt-6 mb-2">Lost your key?</h2>
      <p>You must request a new one from Hebi staff or buy one via Discord.</p>
    </div>
  );
}
